name: examples
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-333.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  #for learning cubit and sqflite
  path: ^1.8.3
  bloc: ^8.1.2
  meta: ^1.9.1
  sqflite: ^2.3.0
  bloc_concurrency: ^0.2.2
  equatable: ^2.0.5

  #for http
  http: ^1.1.0
  stream_transform: ^2.1.0
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

